export const ADD_BUDGET_REQUEST = 'ADD_BUDGET_REQUEST'
export const ADD_BUDGET_SUCCESS = 'ADD_BUDGET_SUCCESS'
export const ADD_BUDGET_FAILURE = 'ADD_BUDGET_FAILURE'

export const LOAD_BUDGETS_REQUEST = 'LOAD_BUDGETS_REQUEST'
export const LOAD_BUDGETS_SUCCESS = 'LOAD_BUDGETS_SUCCESS'
export const LOAD_BUDGETS_FAILURE = 'LOAD_BUDGETS_FAILURE'
